apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ide5l5psf-python
  janus-idp.io/tekton: ide5l5psf-python
  backstage.io/kubernetes-id: ide5l5psf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ide5l5psf-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
