apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ide5l5psf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ide5l5psf-python 
  name: ide5l5psf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ide5l5psf-python 
